// ==UserScript==
// @name         Calibreweb customizer
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Set width of manga pages
// @author       You
// @match        https://manga/*
// @grant        none
// ==/UserScript==

(function(){"use strict";function setCookie(name,value,dayToExpire){var expDate=new Date;expDate.setDate(expDate.getDate+dayToExpire);value=encodeURIComponent(value)+"; expires="+expDate.toUTCString();document.cookie=name+"="+value}function getCookie(name){var cookieName=name+"=";var decodedCookie=decodeURIComponent(document.cookie);var cookieArray=decodedCookie.split(";");for(var i=0;i<cookieArray.length;i++){var cookie=cookieArray[i];while(cookie.charAt(0)==" "){cookie=cookie.substring(1)}if(cookie.indexOf(cookieName)==0){return cookie.substring(cookieName.length,cookie.length)}}return""}function setWidthForClass(className,width){const elements=document.querySelectorAll(`.${className}`);elements.forEach(element=>{element.style.width=width})}function injectElements(){const titleBar=document.getElementById("titlebar");const container=document.createElement("div");const slider=document.createElement("input");var size=getCookie("page-width");if(size===""){size=1}slider.className="slider";slider.type="range";slider.min=0;slider.max=100;slider.value=100;function change(e){const percentage=parseFloat(e.value)/100;const desiredWidth=`${percentage*100}%`;const className="mainImage";setCookie("page-width",percentage,60);setWidthForClass(className,desiredWidth)}slider.addEventListener("input",function(){change(this)});slider.value=100*size;change(slider);container.appendChild(slider);titleBar.appendChild(container);window.addEventListener("resize",function(){change({value:100*getCookie("page-width")})})}setTimeout(injectElements,500);function handleKeyPress(event){if(event.key==="g"){const page=prompt("Jump to page:");var delta=page-currentImage;if(delta==0)return;var direction="next";if(delta<0){delta=-delta;direction="prev"}for(var i=0;i<delta;i++){if(direction=="prev")showPrevPage();else showNextPage()}currentImage=page}}document.addEventListener("keypress",handleKeyPress);const customCSS=`/* Your CSS styles here */.slider {  -webkit-appearance: none;  width: 100%;  height: 5px;  border-radius: 5px;    background: #d3d3d3;  outline: none;  opacity: 0.7;  -webkit-transition: .2s;  transition: opacity .2s;}.slider::-webkit-slider-thumb {  -webkit-appearance: none;  appearance: none;  width: 15px;  height: 15px;  border-radius: 50%;   background: #04AA6D;  cursor: pointer;}.slider::-moz-range-thumb {  width: 15px;  height: 15px;  border-radius: 50%;  background: #04AA6D;  cursor: pointer;}`;function injectCSS(css){const style=document.createElement("style");style.textContent=css;document.head.appendChild(style)}injectCSS(customCSS)})();